frontend/src/App.tsx
This PR adds the possibility of having expandable submenues in the main menu. We can set the submenus as default open/closed.
When logged in as a SP you are now met with this:
Note that I've also added some icons for some of the basic resources. We can consider adding icons for the rest going forward as well.
A list of available icons are at https://mui.com/material-ui/material-icons/
=> feat: grouping in main menu (FLEX-446)

frontend/src/auth/FieldStack.tsx, frontend/src/auth/InputStack.tsx
Kind of 80/20 solution. Not perfect but very simple.
Other options explored (but more complex and did not manage on the first try) :
- show the tooltip inside the input field, as a Material UI `InputAdornment` ;
- show the tooltip before or after the input field, on the same _horizontal_ line.
> [!NOTE]
> Side feature of this PR. Dividers between fields on show pages makes the UX of tooltips even better IMHO :
>
> ![Screenshot 2025-02-11 100922](https://github.com/user-attachments/assets/a470553a-2d87-4de1-b7ac-5083381a8896)
=> feat(ui): add tooltips to input components (FLEX-456)

db/authz/controllable_unit_accounting_point_end_user.sql, db/authz/controllable_unit_end_user.sql, db/flex/controllable_unit_rls.sql, db/flex/controllable_unit_service_provider_rls.sql, db/flex_structure.sql, justfile
This PR reimplements the RLS using `accounting_point` and `accounting_point_end_user` with an internal security definer view. First experimentation before further refactoring in our database architecture.
> [!NOTE]
> The view is in a distinct `authz` folder with already some logic in the scripts to be able to declare several of them later on. The intent is to isolate such _internal views_ from both _internal tables_ in the `flex` schema and _exposed views_ in the `api` schema.
>
> However, as the added internal view is used to define RLS policies, it still technically belongs to the `flex` schema. We can decide to change that later, but currently the architecture creates a mutual dependency between the `flex` schema and the (potential, future) `authz` schema.
=> feat(db): implement AP(EU) RLS policies with a security definer view (FLEX-445)

db/api/accounting_point_balance_responsible_party.sql, db/api/accounting_point_energy_supplier.sql, db/api_structure.sql, db/authz/controllable_unit_balance_responsible_party.sql, db/authz/controllable_unit_energy_supplier.sql, db/flex/accounting_point_balance_responsible_party.sql, db/flex/accounting_point_balance_responsible_party_history_audit.sql, db/flex/accounting_point_balance_responsible_party_rls.sql, db/flex/accounting_point_energy_supplier.sql, db/flex/accounting_point_energy_supplier_history_audit.sql, db/flex/accounting_point_energy_supplier_rls.sql, db/flex/controllable_unit_rls.sql, db/flex_structure.sql, db/test_data/test_data.sql, docs/resources/controllable_unit.md, test/api_client_tests/test_cu.py, test/api_client_tests/test_cusp.py
Same model as the `CU <-> EU` relation we already have.
No notifications for these users required yet in the processes, so nothing implemented here for now.
=> feat(db): relation between CU and ES + BRP via AP

backend/data/data.go, local/nginx/templates/flex.conf, local/nginx/templates/local.conf
Attempt at moving URL rewrites for single-ID and history pages from nginx to the backend.
=> feat(backend): move URL rewrites from nginx to the backend (FLEX-454)

frontend/src/App.tsx, frontend/src/controllable_unit/ControllableUnitList.tsx, frontend/src/controllable_unit/service_provider/ControllableUnitServiceProviderInput.tsx, test/api_client_tests/test_cusp.py
This PR makes it possible to create a CU-SP contract in the portal without having to choose a CU from the readable ones.
> [!IMPORTANT]
> Funnily, this is only a UI update. CUSP-SP001 covers the need on the db side. Tests already work with SP not being able to read the CU as the added check to the test shows.
=> feat(ui): allow creating a CU-SP from the CU ID (FLEX-470)

backend/event/models.sql, backend/event/models/models.custom.go, backend/event/models/models.sql.go, docs/resources/controllable_unit_service_provider.md
This PR adds notifications for end users behind a controllable unit during the valid time period of a CU-SP contract when this contract changes. Both the end users _before and after_ the update are notified.
This change supports the delete operation on CU-SP because it is a soft delete, _i.e._, turned into an update.
=> feat(backend): notify end user on CU-SP update (FLEX-469)

backend/pgrepl/connection.go
This small change reduces the noise in the backend logs. We can do more or less than that :
⏫ A _harder_ approach would be to also hide the specific log of the event worker acquiring a connection everytime it wants to check the events, but it requires a bit more work because this log is actually useful for other roles in the system.
⏬ A _softer_ approach would be to keep the keepalive logs, but only at the `DEBUG` level, so we can filter this out when checking the logs.
=> feat(backend): lower log level on primary keepalive replication messages (FLEX-464)

frontend/src/ResourceButton.tsx, frontend/src/notice/NoticeList.tsx, frontend/src/notification/NotificationShow.tsx
This PR adds a button to link to the resource at the end of each line in the notice list.
As such buttons exploit the `source` field format which is the same in the `event` and `notice` resources, it made sense to refactor the button we had on the notification page so that it can be used in both use cases.
=> feat(ui): link-to-resource buttons on notice list (FLEX-125)

backend/data/data.go, backend/flex.go
This PR turns the response-rewriting mechanism that runs when coming back from PostgREST into a standard library `ReverseProxy` response modifier.
It means it is no longer a middleware but a part of the PostgREST handler, and we no longer rely on a custom body capture mechanism.
=> feat(backend): PostgREST middleware as stdlib response modifier (FLEX-483)

backend/auth/auth.go, backend/flex.go, backend/internal/trace/trace.go
This PR makes the token middleware use a stdlib signature, going through the wrapper function to remain compatible with Gin.
The middleware still depends on Gin for now, ~~for the abort feature to disable further handling, and~~ to store the decoded token in the context.
=> feat(backend): stdlib signature for token middleware (FLEX-483)

db/api_auth.sql, db/api_field_level_authorization.sql, db/api_structure.sql, db/auth_base.sql, db/flex/entity_rls.sql, db/flex/identity_rls.sql, db/flex/notice.sql, db/flex/party_membership_rls.sql, db/flex/party_rls.sql, db/flex/service_providing_group.sql, db/flex_auth.sql, db/flex_base.sql, db/flex_field_level_authorization.sql, db/flex_reference_data.psql, db/flex_structure.sql, db/flex_test.psql, db/flex_users.sql, db/load.sh, db/pre.sql, docker-compose.yml, justfile, local/backend/dev.env, local/backend/test.env, local/postgres/init.sql
This PR does a few things:
* cleans up role names
* moves role creation out of the db load scripts
* "flex" role now owns all-the-things in the database - no more grants between the schemas. This allows us to more freely chop up functionality into different extension/logic schemas.
* removes the "migrator" role - flex is the owner and will be used for migrations as well
The purpose is to go one step further to provide a good starting point for liquibase.
I'm opening this as a draft because it will break deployment (need to fix that in the flex repo), but it is ready for review.
=> refactor: move db roles as prerequisites to db load

frontend/src/controllable_unit/ControllableUnitList.tsx, frontend/src/controllable_unit/service_provider/ControllableUnitServiceProviderInput.tsx, frontend/src/notification/NotificationList.tsx
Bug detected while working on CU lookup, also an isolated part of the other PR.
Basically we were extracting the party ID from identity with a wrong field name. It's called `partyID`, not `party_id`. I don't know when the bug dates back to, but this fixes it.
=> fix(ui): change in identity party ID field name

backend/auth/auth.go
This transfer of the token from cookie to `Authorization` header was in the former PostgREST handler, and when transitioning to a stdlib format we removed it because this should belong to the token middleware. We just forgot to add it in the other place.
This got under the radar because tests kept working : they don't use the cookie as the OpenAPI client sets the header, so we are never in the problematic situation, as opposed to the frontend app.
=> fix(backend): set Authorization header from cookie in backend (FLEX-497)

frontend/package-lock.json, frontend/src/notification/NotificationList.tsx
Could not reproduce the bug, but the error message suggests we were trying to use the identity even when it is undefined.
Following the [official docs](https://marmelab.com/react-admin/useGetIdentity.html), this PR makes the `NotificationList` component wait for the loading to be done before actually returning a component that uses the identity value as a filter.
=> fix(ui): wait for identity to be loaded before rendering notification list (FLEX-499)

local/authelia/config/configuration.yml
Authelia just released a new version of their software with a breaking change in the claims of the authentication tokens. IIUC, basically they are removing claims from the tokens that are not strictly necessary in the OIDC standard by default. Options were added in the configuration to bypass this and keep tokens as they were in previous versions.
This PR sets such options so that we don't have to care about it for now. We can think about a better solution later, but the local environment is necessary for testing and doing our work, so this shouldn't be in our way IMO, especially given that we just use Authelia in the local environment.
https://www.authelia.com/blog/4.39-release-notes/#id-token-changes
> [!NOTE]
> Another option was to pin v4.38 in the Docker Compose configuration, but …
=> fix(auth): bypass Authelia update to token claims (FLEX-510)

backend/data/models.go, backend/data/models.sql, backend/data/models/models.sql.go, db/api/controllable_unit_lookup.sql, frontend/src/controllable_unit/lookup/ControllableUnitLookupResult.tsx, openapi/openapi-api-base.yml, openapi/openapi-api-no-default.json, openapi/openapi-api.json, test/flex/models/controllable_unit_lookup_response_item.py
This PR removes the `end_user_id` field of the CU lookup response.
First, it is unnecessary, because the user doing the lookup already knows their business ID, so they are likely to know their name. Second, it is a technical ID that does not mean much functionally, and if the user launching the lookup is not allowed to see the associated party, then they cannot even get the name from this ID.
Rød PR altså :wink:
=> feat: remove end user ID from CU lookup response (FLEX-511)

local/nginx/templates/flex.conf
This _should_ make browsers less prone to cache older versions of our portal.
The behaviour in FLEX-512 is still a bit mysterious to me, but at least now we are returning explicit cache headers/etags all over the place.
=> feat: set explicit cache headers on all-the-things (FLEX-512)

docs/test-data.md, local/elements/index.html, local/nginx/templates/flex.conf
Switching to jsdelivr because alpinejs/csp is not available on unpkg
=> fix: use alpinejs/csp to avoid unsafe-eval (FLEX-517)

frontend/package-lock.json, frontend/src/tooltip/FieldTooltip.tsx
Could not reproduce the exact same error message as in the ticket, but I also got an error on history pages, and according to the console it was related to tooltip components not working. At least this one is fixed.
=> fix(ui): make tooltips work on history pages (FLEX-550)

backend/auth/auth.go, backend/auth/authorizationgrant.go, backend/auth/models/models.go, backend/internal/trace/trace.go, db/auth_base.sql, docs/auth.md, justfile, openapi/openapi-auth.yml, test/auth_tests/test_client_credentials.py, test/auth_tests/test_jwt_bearer.py, test/inspect/assume_delete_entity.hurl, test/inspect/assume_delete_success.hurl, test/inspect/assume_missing_party_id.hurl, test/inspect/assume_success.hurl, test/inspect/gen_jwt.py, test/inspect/hurl.sh, test/inspect/session_success.hurl, test/inspect/token_client_credentials_incorrect_client.hurl, test/inspect/token_client_credentials_incorrect_password.hurl, test/inspect/token_client_credentials_success.hurl, test/inspect/token_exchange_success.hurl, test/inspect/token_exchange_unauthorized.hurl, test/inspect/token_userinfo_bad_token.hurl, test/inspect/token_userinfo_entity.hurl, test/inspect/token_userinfo_party.hurl, test/security_token_service.py
This PR makes use of the entity client resource in the actual authentication routes that were previously using client information stored in entity. Client credentials and JWT Bearer authentication methods are updated.
=> feat(auth): use entity client resource in login (FLEX-521)

.teamcity/_Self/NpmProject.kt
The OWASP dependency analysis is currently not working. Temporarily disabling and will re-enable this when the associated Jira task is resolved ([TDX-587](https://elhub.atlassian.net/browse/TDX-587))
[TDX-587]: https://elhub.atlassian.net/browse/TDX-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Disable dependency analysis in NpmProject configuration

db/flex/service_provider_product_application.sql
This PR allows an SP to create several product applications for the same SO. There is actually nothing else to do than lifting a constraint.
No additional constraint on the actual product types was added for now, but we could error if a product type was already applied for in a previous application.
=> feat(db): allow multiple SP product application per SP & SO (FLEX-555)

.golangci.yml, docs-dev/index.md
This PR updates the `golangci-lint` configuration to v2.0.2 (automated update with the `migrate` command, then manual copy of former comments) and updates our docs accordingly. After merging, we need to have an updated `golangci-lint` executable for everything to work.
I ran `cd backend && golangci-lint run` after the update, as pre-commit is configured to do, and it found no issue. So I guess it worked, but I wonder if there is something else to do.
> [!NOTE]
> It seems like uninstalling and re-running our previously documented `go install` command does not manage to get this new version. I checked the official docs and the method is actually [not recommended](https://golangci-lint.run/welcome/install/#install-from-sources) anyway.
>
> There are basically two alternatives : downloading …
=> chore: upgrade golangci-lint to v2.0.2 (FLEX-554)

db/flex/balance_responsible_party_metering_grid_area.sql, db/flex/balance_responsible_party_metering_grid_area_rls.sql, db/flex_structure.sql, db/test_data/test_data.sql
This PR adds the link corresponding to the [eSett data linked in the ticket](https://opendata.esett.com/rbr).
For now, no valid time, no history : as simple as possible...
After discussion, "retailer" sounded like an eSett-specific name and quite unclear in our context. For now I am keeping the naming trivial from the content of the table. Can be renamed later.
=> feat(db): associate BRPs to metering grid areas (FLEX-486)

backend/auth/auth.go, docker-compose.yml, test/other_tests/test_jwt_crypto.py
So it turns out that PostgREST prior to v13 had _undocumented_ support for HS384. v13 swithches underlying jwt handling lib and lost that support.
Docs are very clear (and have always been).
https://docs.postgrest.org/en/v13/references/auth.html
>  jwt-secret. If it is set to a simple string value like “reallyreallyreallyreallyverysafe” then PostgREST interprets it as an HMAC-SHA256 passphrase.
So we then just go with HS256 which is actually good enough for us.
Got to read some haskell so this was a fun bughunt 🚀
=> fix: tokens must use HS256 alg for PostgREST v13 (FLEX-583)

db/flex/replication/slots.sql
Allows keeping the `runAlways` and running `just reload` without getting an error.
=> fix(db): create replication "if not exists" (FLEX-602)

db/flex/controllable_unit.sql
This PR overrides the checksum for the CU table definition, so that Liquibase ignores the change (the definition is there only for documentation anyway, because only the migration is run).
I moved before the migration and ran Liquibase with both the migration and the update in the table definition, in order to get the error message that gives us the checksum we need to use.
=> fix(db): override checksum for DB table definition (FLEX-588)

backend/auth/auth.go
Log entity/party/identity in all 3 subhandlers for `/token`: client credentials, token exchange, JWT bearer.
=> feat(backend): log user details after successful call to /token (FLEX-604)

db/flex/changelog.yml, local/postgres/init.sql
This PR adds a `flex_operation_readonly` role that can _only read_ the `flex` schema.
=> feat(db): add read-only role in local database (FLEX-606)

frontend/src/App.tsx
Component based on the stock [`ResourceMenuItem`](https://github.com/marmelab/react-admin/blob/9d43f2d114d96e22a9a7e563fb7de9b03fdb081d/packages/ra-ui-materialui/src/layout/ResourceMenuItem.tsx#L14), but for some reason it ignores other props than `name` so we cannot override the label directly.
=> feat(ui): shorter resource names in portal menu (FLEX-535)

db/flex/controllable_unit_service_provider_migrations.sql
This PR fixes the next part of the CUSP delete bug.
The previous migration set a field as generated, but fields in the history table should not have any of these mechanisms, because all fields just get copied from the main table. The trigger inserting in history on CUSP delete is therefore failing on prod ATM.
I tested the additional SQL line and the precondition on a dummy table with a generated field, but it is harder to test than the previous migrations we have written because the state in which we want to test this does not exist on local. Indeed, locally, the reset defines the table with the extra field and the history is created with `LIKE`, without constraints. So locally the problem cannot show.
=> fix(db): no generated field in CUSP history (FLEX-622)

db/flex/controllable_unit_service_provider_migrations.sql
Apparently, comments are counted when computing a checksum for a migration...
NB: this migration has already been run and won't run again thanks to the precondition. It's just to get the comment change accepted by liquibase.
=> fix: correct migration checksum after comment edit (FLEX-622)

backend/internal/middleware/defaultquerylimit.go
Our portal is doing requests like
> GET | https://flex-test.elhub.no/api/v0/party?id=in.(405,404,6,16,534,15,535,527,526,519,518,511,510,503,502,495,494,487,486,479,478,471,470,463,462,455,454,447,446,439,438,431,430,423,422,414,413,397,396,389,388,381,380,373,372,365,364,357,356,349,348,341,340,333,332,324,323,316,315,307,306,299,298,291,290,283,282,275,274,266,265,258,257,250,249,242,241,234,233,226,225,218,217,210,209,202,201,194,193,186,185)
~90 parties. The default limit is at 50, so stuff "disappear" in the frontend.
=> feat: 4x default query limit (FLEX-664)

frontend/src/controllable_unit/balance_responsible_party/ControllableUnitBalanceResponsiblePartyList.tsx, frontend/src/controllable_unit/energy_supplier/ControllableUnitEnergySupplierList.tsx, frontend/src/controllable_unit/service_provider/ControllableUnitServiceProviderList.tsx, frontend/src/controllable_unit/technical_resource/TechnicalResourceList.tsx, frontend/src/entity/client/EntityClientList.tsx, frontend/src/party/membership/PartyMembershipList.tsx, frontend/src/service_provider_product_application/comment/ServiceProviderProductApplicationCommentList.tsx, frontend/src/service_providing_group/grid_prequalification/ServiceProvidingGroupGridPrequalificationList.tsx, frontend/src/service_providing_group/membership/ServiceProvidingGroupMembershipList.tsx, frontend/src/service_providing_group/product_application/ServiceProvidingGroupProductApplicationList.tsx
This PR fixes pagination on all list pages used as subresources, and removes our manual calls to `useGetList` when we can go through the built-in call in the `List` component.
Basically, fixing pagination keeping the manual calls to `useGetList` would have forced us to override pagination in all pages with such a manual call. In the end, you just reimplement the whole list controller on top of the existing one. This felt wrong.
Such manual calls were initially a way to introduce filtering (unnecessary though, we could just have gone with the `filter` prop in `List`), and they became crucial to fix the sorting in the [previous PR](https://github.com/elhub/flex-information-system/pull/243), because they allowed avoiding a weird behaviour of React-Admin on pages with several lists:  _[quoted …
=> fix(ui): fix pagination in lists of subresources (FLEX-663)

db/auth/functions.sql
This PR adds default scopes when the entity assumes a party they _own_.
We give the required scopes for the API to function correctly, among which read-write access to data (it makes sense to have some sort of regular access at least, when you own the party).
=> feat: set default scopes when doing login through party ownership (FLEX-692)

backend/event/models.sql, backend/event/models/models.custom.go, backend/event/models/models.sql.go, backend/internal/validate/validate.go, db/flex/event_rls.sql, db/flex/service_provider_product_application.sql, docs/resources/event.md, docs/resources/service_provider_product_application_comment.md, docs/resources/service_provider_product_suspension_comment.md, test/api_client_tests/test_cu.py, test/api_client_tests/test_entity.py, test/api_client_tests/test_event.py, test/api_client_tests/test_service_provider_product_suspension.py
This PR adds notifications for _SP product suspension comments_ and restores full RLS test coverage (some stuff had been forgotten).
=> feat: notifications for SPPS comments (FLEX-733)

db/flex/technical_resource_rls.sql, docs-dev/editing-resources.md, docs/resources/technical_resource.md
This PR adds docs based on the work done updating the RLS for deletable resources.
I checked the last resource we had to update before events (technical resource), and there was nothing more to do actually. The resource docs were wrong, but the implementation was already the one we want for now. So I just updated the docs. As mentioned in the other PR (https://github.com/elhub/flex-information-system/pull/302#discussion_r2378352720), it is possible to design a more precise policy, but it is not needed for now.
=> docs: update docs with advice on RLS creation (FLEX-728)

test/api_client_tests/test_party_membership.py
`read:data` will be given in realistic cases. This simplifies the test and removes the useless TODO.
=> test: give read:data scope to org admin in PM test (FLEX-744)

db/flex/event_rls.sql, test/api_client_tests/test_event.py
This PR fixes RLS for the event resource so that we can still read create events and delete events even after removal of a row in a deletable resource.
=> fix: make event policies on deletable resources history-based (FLEX-728)

justfile, test/api_client_tests/test_cu.py, test/api_client_tests/test_cu_lookup.py, test/api_client_tests/test_cusp.py, test/api_client_tests/test_entity_lookup.py, test/api_client_tests/test_event.py, test/api_client_tests/test_spg.py, test/api_client_tests/test_spg_grid_prequalification.py, test/api_client_tests/test_spg_membership.py, test/api_client_tests/test_spg_product_application.py, test/api_client_tests/test_technical_resource.py
This PR makes the tests independent from ranking of entities/parties to point at the test end user, which makes them green again.
It also fixes a latent bug we had when setting hardcoded entity client IDs for some of the test users. Indeed, everything used to go fine because there was probably one entity client per entity in the test set, so IDs were aligned and we did not notice the wrong field there.
=> fix(test): remove hardcoded IDs for end user in tests

db/flex/entity_client_migrations.sql, db/flex/entity_client_rls.sql, docs/resources/entity_client.md, test/api_client_tests/test_entity_client.py
This PR restricts our definition of _human user_ (for access to entity clients as organisation party) to both the following checks:
- the current entity is a _person_ entity;
- user _not_ logged in through an entity client.
The first condition was already being checked, the second is now checked by reading the current identity (possible since #274).
As also explained in a comment, by restricting to human users, we lose the ability to test the positive case of this policy, but testing manually shows this works.
> [!NOTE]
> On the side, I noticed that our trigger restricting `party_id` on entity clients was not running on insert. This is now fixed. It is not a critical fix, because anyway we do that kind of check server-side (`auth.assume_party`), but it reduces confusion.
> If `party_id` …
=> feat(db): make definition of human user stricter for ECL-ORG002 (FLEX-691)

docs-dev/documentation.md, docs-dev/tooling.md, docs/guides/get-ready-for-market.md
I moved it up a bit. Looks like this now:
=> docs: fix alert in get ready for market to GH style
